convert all pages for Cadmus to PDF 1.3
git-svn-id: svn://tug.org/tugboat/trunk@754 7237770a-693a-0410-b4d3-c34f48dbc3f6

diff --git a/misc/make-issue-pages-tub b/misc/make-issue-pages-tub
--- a/misc/make-issue-pages-tub
+++ b/misc/make-issue-pages-tub
@@ -94,8 +94,7 @@ assert_pdfpagecount () {
 }
 
 # 
-# We do some unusual Ghostscript calls, so don't use ps2pdf-tub.  But
-# tell gs not to rotate our pages (e.g., tb132voss-hvfloat, but
+# Tell gs never to rotate our pages (e.g., tb132voss-hvfloat, but
 # auto-rotation is a bad idea in general).
 gs="gs -q -dBATCH -dAutoRotatePages=/None"
 # Can't use -dNODISPLAY because that eliminates split output.
@@ -176,8 +175,9 @@ for page in `seq --format="%03.0f" 1 $filecount`; do # for every page in doc
       ps2pdf-gray-tub $origfile $grayfile || exit 1
       mv $grayfile $origfile || exit 1
     else
-      #echo "$page: no color on page ($colorvals), continuing."
-      :
+      echo "$page: no color on page, converting to pdf-1.3."
+      ps2pdf-tub -13 $origfile 13$origfile || exit 1
+      mv 13$origfile $origfile || exit 1
     fi
     gray_count=`expr $gray_count + 1`
   fi
@@ -194,6 +194,8 @@ echo "$0: $color_count color + $gray_count grayscale  =  $filecount pages."
 
 # 
 # Link the covers and the spine, we should not need any changes.
+# We could convert to PDF 1.3 but in practice these files don't do
+# anything unusual.
 echo "$0: linking covers ... (in `pwd`)"
 for c in 1 2 3 4; do
   dest=c$c$filesuffix.pdf
@@ -211,14 +213,16 @@ ln -s ../spine.pdf sp$filesuffix.pdf || exit 1
 assert_pdfpagecount sp$filesuffix.pdf 1
 
 # Finally, re-concatenate all the pages, so that we have a single file
-# we can look through and check that grayscale vs. color came out correctly.
+# we can look through and check that grayscale vs. color came out correctly,
+# etc. Omit the covers and spine, better to look at those separately.
 echo "$0: making issue-upload.pdf for manual check ..."
-if pdfconcat issue-upload.pdf [^cs]*$filesuffix.pdf; then
+if pdfconcat-tub -13 issue-upload.pdf [^cs]*$filesuffix.pdf; then
   assert_pdfpagecount issue-upload.pdf $filecount
   status=0
 else
-  echo "$0: pdfconcat failed, exiting with error." >&2
+  echo "$0: pdfconcat-tub failed, exiting with error." >&2
   status=1
 fi
 ls -l issue-upload.pdf
+pdfversion issue-upload.pdf
 exit $status
