\tburl like \tbsurl; pdfcrop multiple files; \sec define \newline
git-svn-id: svn://tug.org/tugboat/trunk@455 7237770a-693a-0410-b4d3-c34f48dbc3f6

diff --git a/misc/pdfcrop-tub b/misc/pdfcrop-tub
--- a/misc/pdfcrop-tub
+++ b/misc/pdfcrop-tub
@@ -4,9 +4,17 @@
 # 
 # Excise the "PDFCROP" version line, preserve exit status.
 
-out=${TMPDIR-/tmp}/pdfcroptub.$$
-pdfcrop "$@" >$out
-status=$?
-grep -v '^PDFCROP 1\.' $out
+for f in "$@"; do
+  out=${TMPDIR-/tmp}/pdfcroptub.$$
+  pdfcrop "$f" >$out
+  status=$?
+  grep -v '^PDFCROP 1\.' $out
+  if test $status != 0; then
+    echo "$0: failed on: $f" >&2
+    cat $out
+    exit $status
+  fi
+done
+
 rm -f $out
-exit $status
+exit 0
