handle structured citations, register dois for tb127=44:1, ignore spaces after control words in bb subtitles, remove crossbib attempt
git-svn-id: svn://tug.org/tugboat/trunk@650 7237770a-693a-0410-b4d3-c34f48dbc3f6

diff --git a/capsules/cr-copy-bbl-abs b/capsules/cr-copy-bbl-abs
--- a/capsules/cr-copy-bbl-abs
+++ b/capsules/cr-copy-bbl-abs
@@ -1,14 +1,20 @@
 #!/bin/sh
 # $Id$
-# Copy .bbl files for Crossref. Public domain.
+# Copy helper (bbl.tex, abs.tex, .aux, .bib) files for Crossref. Public domain.
 # 
-# As a first step toward preparing the <citation_list> elements for the
-# Crossref upload (see ltx2crossrefxml, crossref/README, etc.), we copy
-# all bbl and abstract files for a given issue $1 to the temporary
-# holding directory $2.
+# As a first step toward preparing a Crossref upload (see
+# ltx2crossrefxml, crossref/README, etc.), we copy all helper files for
+# a given issue $1 to the temporary holding directory $2.
 # 
+# These so-called helper files include bbl.tex and abs.tex (created by
+# hand), and *.aux and *.bib (as written). Any or all may not exist for
+# a given article, but there will (presumably) be at least one of each
+# type for an entire issue. (If that assumption fails, have to change
+# the checks below not to exist.)
+
 # We're going to assume there are no spaces in filenames,
 # cp supports -p, and other such non-portabilities.
+cp="cp -pf" # -v
 
 if test $# -ne 2; then
   echo "Usage: $0 CAPSULE.txt OUTPUTDIR" >&2
@@ -63,25 +69,31 @@ if test $abs_count -eq 0; then
   exit 1
 fi
 #
-# structured crossref not ready.
-#crb_count=`ls -1 $issdir/*/crossbib.xml 2>/dev/null | wc -l`
-#if test $crb_count -eq 0; then
-#  echo "$0: no crossbib.xml files found under: $issdir" >&2
-#  exit 1
-#fi
+aux_count=`ls -1 $issdir/*/*.aux 2>/dev/null | wc -l`
+if test $aux_count -eq 0; then
+  echo "$0: no aux files found under: $issdir" >&2
+  exit 1
+fi
+#
+bib_count=`ls -1 $issdir/*/*.bib 2>/dev/null | wc -l`
+if test $bib_count -eq 0; then
+  echo "$0: no bib files found under: $issdir" >&2
+  exit 1
+fi
 
 # We intentionally do not erase existing files or move them aside;
 # another level (namely the cr-do-issue script) does that.
 
-# Separate the bbl used for the doi stuff from the one used by TeX; that
-# is, we manually copy or create bbl.tex in each item directory, and
-# then save it as tbNNNIDENT.bbl when copying into our output directory.
-# ltx2crossrefxml looks for it with that name.
+# Separate the bbl used for the doi stuff from the one used by TeX,
+# since it often needs editing; that is, we manually copy or create
+# bbl.tex in each item directory, and then save it as tbNNNIDENT.bbl
+# when copying into our output directory. ltx2crossrefxml looks for it
+# with the latter name.
 #
 for b in $issdir/*/bbl.tex; do
   ident=`basename \`dirname "$b"\``
   dest=$outdir/tb${seqno}${ident}.bbl
-  cp -pf "$b" "$dest" || exit 1
+  $cp "$b" "$dest" || exit 1
 done  
 
 # Similarly for abstracts.
@@ -89,17 +101,40 @@ done
 for a in $issdir/*/abs.tex; do
   ident=`basename \`dirname "$a"\``
   dest=$outdir/tb${seqno}${ident}.abs
-  cp -pf "$a" "$dest" || exit 1
+  $cp "$a" "$dest" || exit 1
 done  
 
-# Similarly for the structured crossref bib files. (not ready)
+# Similarly for the aux files.
 # 
-#for a in $issdir/*/crossbib.xml; do
-#  ident=`basename \`dirname "$a"\``
-#  dest=$outdir/tb${seqno}${ident}.crbib
-#  cp -pf "$a" "$dest" || exit 1
-#done  
+for a in $issdir/*/*.aux; do
+  ident=`basename \`dirname "$a"\``
+  dest=$outdir/tb${seqno}${ident}.aux
+  $cp "$a" "$dest" || exit 1
+done  
 
-#echo "$0: $bbl_count bbl(s), $abs_count abs(s), $crb_count crossbib(s) copied: $outdir"
-echo "$0: $bbl_count bbl(s), $abs_count abs(s) copied: $outdir"
+# But for the bib files, preserve the original names,
+# since that is what the aux file refers to.
+# Since those names are random, copy them all into a subdir bib/
+#  instead of cluttering up the main $outdir. The Makefile sets
+#  TEXMFDOTDIR to find them there.
+# Also, exclude save*.bib, since those are temp files we create during editing.
+# Also, if there are any duplicate names, quit. Processing
+#  can't succeed if there are two bib files by the same name,
+#  since we're copying everything into a single working directory.
+# 
+for bib in $issdir/*/*.bib; do
+  bib_basename=`basename "$bib"`
+  echo "$bib_basename" | grep '^save' >/dev/null && continue
+  dest=$outdir/bib/$bib_basename
+  if test -e "$dest"; then
+    echo "$0: bib file already exists: $dest" >&2
+    echo "$0:      trying to copy new: $bib" >&2
+    echo "$0: this must be rectified to continue, goodbye." >&2
+    exit 1
+  fi
+  test -d "$outdir"/bib || mkdir "$outdir"/bib
+  $cp "$bib" "$dest" || exit 1
+done  
+
+echo "$0: $bbl_count bbl, $abs_count abs, $aux_count aux, $bib_count bib copied: $outdir"
 exit 0
